# Generated by Django 3.2.7 on 2021-09-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Context', models.TextField()),
                ('Image', models.TextField()),
                ('UploadTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['UploadTime'],
            },
        ),
    ]
