# Generated by Django 3.2.7 on 2021-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadTime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('context', models.TextField(max_length=400)),
                ('photo_URL', models.URLField()),
            ],
            options={
                'ordering': ['UploadTime'],
            },
        ),
    ]
